### ISSUE TITLE
$media->getUrl() triggers errors after upgrading to Version 3

### ISSUE THREAD

**Issue by hasnatbabur** [plank/laravel-mediable#143] opened 2019-09-17 11:16 UTC
Several trouble after upgrading to laravel version 6 and laravel-mediable version 3.

Please note that everything was passing before upgrading to V 3.

I am testing on local public disk. During test I was accessing $media->getUrl() and facing errors.

When I do Storage:fake():
Storage::fake();
$uploadedFile = UploadedFile::fake()->image('photo.jpeg', 20, 20);

I am getting following error (formatted):
"message:"
"strpos() expects parameter 1 to be string, bool given"
"exception:"
"Symfony\Component\Debug\Exception\FatalThrowableError"
"file:"
"/var/www/watchcrunch/vendor/plank/laravel-mediable/src/UrlGenerators/LocalUrlGenerator.php"
"line:"
100
"trace-first:"
array:3 [
  "file" => "/var/www/watchcrunch/vendor/plank/laravel-mediable/src/UrlGenerators/LocalUrlGenerator.php"
  "line" => 100
  "function" => "strpos"
]

When I don't fake Storage:fake()
//Storage::fake();
$uploadedFile = UploadedFile::fake()->image('photo.jpeg', 20, 20);

I am getting following error (formatted):
"message:"
"Media file `/var/www/watchcrunch/storage/app/public/photos/2019/09/O1TtRmb6kBfBCyQsfCgAXGiBCCFfOubbeoxgH0H2.jpeg` is not part of the public path `/var/www/watchcrunch/public`"
"exception:"
"Plank\Mediable\Exceptions\MediaUrlException"
"file:"
"/var/www/watchcrunch/vendor/plank/laravel-mediable/src/Exceptions/MediaUrlException.php"
"line:"
26
"trace-first:"
array:5 [
  "file" => "/var/www/watchcrunch/vendor/plank/laravel-mediable/src/UrlGenerators/LocalUrlGenerator.php"
  "line" => 44
  "function" => "mediaNotPubliclyAccessible"
  "class" => "Plank\Mediable\Exceptions\MediaUrlException"
  "type" => "::"
]
-------
After some further digging I found, my file is not considered as public at all although disk has public visibility and even adding makePublic() during upload.

Also I guess the issue may be in LocalUrlGenerated function isInWebroot().

However for S3 driver everything works well as expected.

Can anyone help? Thanks.

**Comment by frasmage** [comment] 2019-09-18 12:58
Hi @hasnatbabur,

I'm pretty sure I know what broke this. I was having a lot of trouble with a particular test consistently failing in CI, but passing locally. I've opened a PR reverting the attempted fix, I'll try to figure out what's going on with that CI environment and put out a patch as soon as I can.

**Comment by frasmage** [comment] 2019-09-18 14:45
Fix is now merged.

**Comment by hasnatbabur** [comment] 2019-09-18 19:11
@frasmage Thanks for merging.
However I am getting same error after updating this package.

And when I do fake storage:
There was 1 error:
1) Tests\Feature\Media\FileUploadTest::test_authenticated_user_can_upload_files
TypeError: strpos() expects parameter 1 to be string, bool given

/var/www/watchcrunch/vendor/plank/laravel-mediable/src/UrlGenerators/LocalUrlGenerator.php:100
/var/www/watchcrunch/vendor/plank/laravel-mediable/src/UrlGenerators/LocalUrlGenerator.php:33
/var/www/watchcrunch/vendor/plank/laravel-mediable/src/UrlGenerators/LocalUrlGenerator.php:43
/var/www/watchcrunch/vendor/plank/laravel-mediable/src/UrlGenerators/LocalUrlGenerator.php:61
/var/www/watchcrunch/vendor/plank/laravel-mediable/src/Media.php:206
/var/www/watchcrunch/tests/Feature/Media/FileUploadTest.php:119

And when I don't fake storage:
There was 1 error:
1) Tests\Feature\Media\FileUploadTest::test_authenticated_user_can_upload_files
Plank\Mediable\Exceptions\MediaUrlException: Media file `/var/www/watchcrunch/storage/app/public/photos/2019/09/photo.jpeg` is not part of the public path `/var/www/watchcrunch/public`

/var/www/watchcrunch/vendor/plank/laravel-mediable/src/Exceptions/MediaUrlException.php:26
/var/www/watchcrunch/vendor/plank/laravel-mediable/src/UrlGenerators/LocalUrlGenerator.php:44
/var/www/watchcrunch/vendor/plank/laravel-mediable/src/UrlGenerators/LocalUrlGenerator.php:61
/var/www/watchcrunch/vendor/plank/laravel-mediable/src/Media.php:206
/var/www/watchcrunch/tests/Feature/Media/FileUploadTest.php:119

---------

For the media url test instead of $media->getUrl() I had to use Storage::url($media->getDiskPath()).

Thanks.

**Comment by ls-sean-fraser** [comment] 2019-09-18 19:39
For the second one, the bug that I had in my tests is that it seems like Laravel 6.0 changed disks to default to private visibility, so I needed to explicitly define that. Can you verify that you are defining this in your config?

I haven't played with fake storages yet. I'm guessing the `realpath()` call is what's getting in the way there (returns false if the file doesn't exist). A fake storage obviously doesn't coincide with the actual disk, so that's probably the cause of the failure. I can remove the realpath calls if you aren't able to find another way around it.

**Comment by frasmage** [comment] 2019-09-22 00:14
@hasnatbabur, were you able to resolve your issues?

**Comment by hasnatbabur** [comment] 2019-09-22 12:00
@frasmage Very thanks for checking in. 

I had to call Storage class for media url everywhere. And everything working fine now.

```
/* todo: is $media->getUrl() fixed? */
//$mediaUrl = $media->getUrl(); // did not work
$mediaUrl = Storage::url($media->getDiskPath()); // returns valid image url
```
Error was:
Plank\Mediable\Exceptions\MediaUrlException: Media file `/var/www/watchcrunch/storage/app/public/photos/2019/09/photo.jpeg` is not part of the public path `/var/www/watchcrunch/public`

I will try to solve the issue on package scope if I can. Thanks again. Cheers.

**Comment by hailwood** [comment] 2019-09-30 00:00
Hey everyone,

The issue is file permissions and it's a change in flysystem.
Specifically the call to `getVisibility()` now checks file and directory permissions to determine if the file/directory is publicly visible instead of relying on the `visibility` key of the disk.

Here is the relevant code, noting that permissionsMap looks like

```php
[
    'file' => [
        'public'  => 420, // 0644
        'private' => 384, // 0600
    ],
    'dir' => [
        'public'  => 493, // 0755
        'private' => 448, // 0700
    ],
]
```

```php
public function getVisibility($path)
{
    $location = $this->applyPathPrefix($path);
    clearstatcache(false, $location);
    $permissions = octdec(substr(sprintf('%o', fileperms($location)), -4));
    $type = is_dir($location) ? 'dir' : 'file';
    foreach ($this->permissionMap[$type] as $visibility => $visibilityPermissions) {
        if ($visibilityPermissions == $permissions) {
            return compact('path', 'visibility');
        }
    }
    $visibility = substr(sprintf('%o', fileperms($location)), -4);
    return compact('path', 'visibility');
}
```

**Basically for your directories to be considered public they need to be chmodded to 755 and files to 644.**

Technically for private they should be 700 and 600 respectively, but because the system defaults to private if it doesn't understand the permissions then it just goes "🤷‍♂️ private I guess"

**Comment by grafikkaos** [comment] 2019-09-30 12:18
I am hoping for a fix to this problem and it's affecting my current app.  Just can't seem to find a way to resolve this issue.  I am unable to use @hasnatbabur solution as I have different sizes for my images.

```php
public function getSquareThumbAttribute()
    {
        return $this->hasMedia('square') ? $this->getMedia('square')->first()->getUrl() : null;
    }
```

So any ideas on resolving this problem, would be great.

**Comment by hasnatbabur** [comment] 2019-09-30 12:32
@frasmage 
Hi, will you please just use 
`Storage::url($this->getDiskPath());`
`Storage::url($media->getDiskPath());`
in $media->getUrl() method for temp quick fix. 
That method should return valid url for all cases.
Thanks.

**Comment by hailwood** [comment] 2019-09-30 20:38
@grafikkaos did you try chmodding as mentioned in my comment above? (note 777 won't work here!).

**Comment by frasmage** [comment] 2019-09-30 22:38
Ageed that we should probably sync up with the underlying Laravel Filesystem/Flysystem change, though that would be a slightly breaking change as it looks this will remove support for the "prefix" config option, and require a "url" option to be defined on the disk (otherwise you get a root-relative URL instead of an absolute URL). 

I will try to put up a PR tomorrow.

**Comment by hailwood** [comment] 2019-10-03 00:39
In the meantime, here's a quick command that should fix it for people running into this issue

```bash
php artisan storage:permissions
```


```php
<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\Storage;
use League\Flysystem\Adapter\AbstractAdapter;

class StoragePermissionsCommand extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'storage:permissions';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Setup storage permissions';

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Execute the console command.
     *
     * @return void
     */
    public function handle()
    {
        $fileSystem = Storage::createLocalDriver(['root' => storage_path()]);

        $this->comment('Setting permissions on directories & files...');
        $this->getOutput()->newLine();

        $directories = $fileSystem->allDirectories();
        $files       = $fileSystem->allFiles();

        $progressBar = $this->getOutput()->createProgressBar(count($directories) + count($files));

        foreach ($directories as $directory) {
            $fileSystem->setVisibility($directory, AbstractAdapter::VISIBILITY_PUBLIC);
            $progressBar->advance();
        }

        foreach ($files as $file) {
            $fileSystem->setVisibility($file, AbstractAdapter::VISIBILITY_PUBLIC);
            $progressBar->advance();
        }

        $this->getOutput()->newLine(2);
        $this->info(sprintf(
            "Set permissions on %s files and %s directories.",
            number_format(count($files)),
            number_format(count($directories))
        ));
    }
}
```

**Comment by frasmage** [comment] 2019-10-03 03:42
Hey guys,

I've put up a PR to move to the underlying filesystem's url() method, removing a lot of the old logic that I had originally written for an older version of Laravel. This is definitely a breaking change, so I will need to tag a new major version.

Anyone interested in testing out the branch to make sure this solution covers all of the bases discussed here?

**Comment by hasnatbabur** [comment] 2019-10-03 15:11
@frasmage Thanks for version 4. I will test this version in few days in my app which uses version 3 with some hacks.

**Comment by frasmage** [comment] 2019-10-11 19:46
Sorry for the delay gent, I had missed the notification that @hailwood wasn't going to be able to complete his PR on time. I've gone ahead with merging and tagging 4.0.0. Enjoy!

**Closed by frasmage** 2019-10-11 19:46 UTC
